# Supabase PostgreSQL connection
spring.datasource.url=jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.dgfmbzbauionhlhvynsj
spring.datasource.password=f^nkybo!indah00d

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Check that Java entities match existing database tables
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.properties.hibernate.default_schema=public

# Small pool is sufficient for development
spring.datasource.hikari.maximum-pool-size=5

spring.h2.console.enabled=false

server.address=0.0.0.0
server.port=8080